version: '3.8'

services:
  api:
    dockerfile: Dockerfile
    context: .
    container_name: my_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
